### ISSUE TITLE
panic: runtime error

### ISSUE THREAD

**Issue by 0xPugal** [musana/fuzzuli#6]
```
root@ubuntu:~# fuzzuli -f subdomains.txt 

  __                               _   _ 
 / _|                             | | (_)
| |_   _   _   ____  ____  _   _  | |  _ 
|  _| | | | | |_  / |_  / | | | | | | | |
| |   | |_| |  / /   / /  | |_| | | | | |
|_|    \__,_| /___| /___|  \__,_| |_| |_|

musana.net | @musana
--------------------------------------------

[*] Scan starting time: 2023-01-01 15:25:21
panic: runtime error: index out of range [1] with length 1

goroutine 8 [running]:
main.shuffle({0xc00001c288, 0x15}, 0x0?)
        /root/go/pkg/mod/github.com/musana/fuzzuli@v1.1.2/fuzzuli.go:183 +0x193
main.getAllCombination({0xc00001c288, 0x15})
        /root/go/pkg/mod/github.com/musana/fuzzuli@v1.1.2/fuzzuli.go:123 +0x311
main.start({0xc00001c288, 0x15})
        /root/go/pkg/mod/github.com/musana/fuzzuli@v1.1.2/fuzzuli.go:98 +0x9c
main.main.func1()
        /root/go/pkg/mod/github.com/musana/fuzzuli@v1.1.2/fuzzuli.go:88 +0x25
github.com/gammazero/workerpool.startWorker(0x0?, 0xc00006a0c0)
        /root/go/pkg/mod/github.com/gammazero/workerpool@v1.1.2/workerpool.go:233 +0x22
created by github.com/gammazero/workerpool.(*WorkerPool).dispatch
        /root/go/pkg/mod/github.com/gammazero/workerpool@v1.1.2/workerpool.go:195 +0x25a
```

**Comment by musana** [comment]
Could you check content of subdomains.txt file? It can contain a blank line. Also, domains in subdomain.txt should start with http:// or https://.

**Comment by 0xPugal** [comment]
@musana Thank you! Now its working
